### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by Boris-Moskovskiy** [Fedorov113/Genome-Complexity-Browser#10]
Не получается запустить GCB_package. не находится модуль 'pandas'. 
После установки всех компонентов запускаю python3 gcb_server.py и программа выдаёт сообщение о том, что Traceback (most recent call last):
  File "gcb_server.py", line 1, in <module>
    from app import app
  File "/home/boris/Downloads/GCB_package/app/__init__.py", line 8, in <module>
    from app import routes
  File "/home/boris/Downloads/GCB_package/app/routes.py", line 3, in <module>
    from app.manage_db import get_complexity_from_db, get_coordinates_from_db, get_operons, get_windows_from_db
  File "/home/boris/Downloads/GCB_package/app/manage_db.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by DNKonanov** [comment]
актуальная версия GCB-сервера по [ссылке](https://github.com/DNKonanov/GCB)
вы можете посетить web-версию по адресу [gcb.rcpcm.org](gcb.rcpcm.org)
ваша проблема решается, как правило, с помощью  
`pip install pandas`
